### ISSUE TITLE
Question: Async client?

### ISSUE THREAD

**Issue by antidata** [scanamo/scanamo#1118]
Hi all,

I would like to know how to use the Async client, I only found examples with the sync one.

Thank you

**Comment by antidata** [comment]
@scala-steward Any comments? Thank you

**Comment by regiskuckaertz** [comment]
@antidata hello - to use the async client, you need to first create a `DynamoDbAsyncClient`:
```scala
val asyncClient = ScanamoAsync(dynamoDbAsyncClient)
```
The API is the same as the sync client, except that the return type is wrapped in [`Future`](https://www.scala-lang.org/api/2.12.x/scala/concurrent/Future.html), so you need to update your code accordingly:
```scala
asyncClient.exec(operation).flatMap { result => 
  ??? // do something with result here.
}
```

**Comment by antidata** [comment]
@regiskuckaertz Thank you!!
