### ISSUE TITLE
Cats Effect 3 migration roadmap/plans ?

### ISSUE THREAD

**Issue by spavikevik** [scanamo/scanamo#1158]
I'm curious if anyone knows what's the plan for supporting `cats-effect` 3? 

Seems the migration from 2 to 3 might be a bit involved, but I could perhaps give it a try if I get some spare time, unless you have other plans and would rather wait... Please let me know.

**Comment by rtyley** [comment]
Hi @spavikevik, an upgrade to Cats Effect 3 was merged with https://github.com/scanamo/scanamo/pull/1166, a few days after this issue was opened! This has now been released with Scanamo [v1.0.0-M16](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M16).

**Comment by keynmol** [comment]
Hi!

Given that CE2 and CE3 are source and binary incompatible, this would mean that all the users of M15 will not be able to upgrade to M16 without a very costly CE2 -> CE3 upgrade (i.e. all the Monix users are cut off by the M16, as Monix is not built for CE3).

The actual CE layer in scanamo is very small, so it should theoretically be possible to publish `-ce2` and `-ce3` modules from the same codebase - would you accept such a PR @rtyley @regiskuckaertz ?
