### ISSUE TITLE
CI for the Scanamo repo not running since 15th June 2021 (`travis-ci.org` decommisioned)

### ISSUE THREAD

**Issue by rtyley** [scanamo/scanamo#1184]
Scanamo has a [`.travis.yml`](https://github.com/scanamo/scanamo/blob/10911aa233f6784aeed278a5160bc134ef512264/.travis.yml) file, but is currently on _travis-ci.**org**_ (ie https://travis-ci.org/github/scanamo/scanamo), which stopped doing builds on 15th June 2021:

![image](https://user-images.githubusercontent.com/52038/129045176-31d25f31-394e-4303-85f4-b3c09e42e475.png)

Although commits since then in the Scanamo repo have been marked with a green tick, this was actually just due to the 'Mergify' check passing (tho' not taking any action):

![image](https://user-images.githubusercontent.com/52038/129048691-88b8ab87-fe61-4b93-a873-c83ed58c7466.png)

...to transfer to _travis-ci.**com**_ (which now also accommodates public open-source repos for free) we'd need to hit the migrate option (and sign up to the beta?) on this page https://travis-ci.com/organizations/scanamo/migrate :

![image](https://user-images.githubusercontent.com/52038/129041458-2eb598e0-2aff-404e-9078-240506c0b32a.png)

I'm not able to do this, as although I'm an 'Admin' on the GitHub repo (https://github.com/scanamo/scanamo/settings/access) I'm not an 'owner' on the GitHub organisation: https://github.com/orgs/scanamo/people

Could I be made an owner on the GitHub organisation? I can then perform the switchover from travis-ci.org to travis-ci.com. I realise also that GitHub Actions is also a popular option these days, personally I'd prefer the switch from `travis-ci.[org -> com]` as it feels like a more minimal change to me.

cc @regiskuckaertz @davidfurey

**Comment by rtyley** [comment]
The CI build is running again, though it's currently failing due to a Monix/Cats conflict causing a `NoClassDefFoundError` error when running `catsEffect/test` :

```
 org.scanamo.ScanamoCatsSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: cats/effect/Sync
[info]   at org.scanamo.ScanamoCatsSpec.$anonfun$new$122(ScanamoCatsSpec.scala:209)
```

The Cats incompatibility would normally be shown by sbt v1.5 like this (but with the current version on the main branch, no warning is given, apparently because the dependencies are marked as `Provided` - see https://github.com/scanamo/scanamo/commit/98fb89e22bf4d10266734898948dfafeeda71254):

```
sbt:root> catsEffect/test
[error] stack trace is suppressed; run last catsEffect / update for the full output
[error] (catsEffect / update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.typelevel:cats-effect_2.12:3.1.1 (early-semver) is selected over {2.5.1, 2.5.1}
[error] 	    +- org.scanamo:scanamo-cats-effect_2.12:1.0.0-M15+109-98fb89e2-SNAPSHOT (depends on 3.1.1)
[error] 	    +- io.monix:monix-catnap_2.12:3.4.0                   (depends on 2.5.1)
[error] 	    +- co.fs2:fs2-core_2.12:2.5.6                         (depends on 2.5.1)
```

I was the one responsible for the Cats Effect v3.1.1 upgrade from v2.5.1 in PR https://github.com/scanamo/scanamo/pull/1166, but missed the Monix/CatsEffect conflict issue :(

Currently, although an updated version of `fs2-core` exists that supports Cats Effect v3.1.1, there has not yet been an updated version of Monix released that supports anything above v2.5.1. I think this leaves two options for fixing the issue:

* Downgrade everything to what Monix supports (ie `cats-effect` v2.5.1, which still uses `cats` v2.6.1, stick with `fs2-core` v2.5.6)
* Drop Monix support for the time being, which essentially means dropping the [`ToIterant`](https://github.com/scanamo/scanamo/blob/c4bed95f34e568ed0fc73828ae929a0ae015f6b5/cats/src/main/scala/org/scanamo/ScanamoCats.scala#L38-L41) method. I couldn't find any open-source uses of this method, though obviously private ones could exist. Personally, I like reducing the size of codebases so I'd personally be fine with losing it, but understand if others consider it important!

**Comment by regiskuckaertz** [comment]
Monix is not being updated nearly often enough anymore so I don't think it will remain relevant for long unless a new maintainer brings it back to life.

**Comment by rtyley** [comment]
With PR #1187 merged, the Travis-CI build is now passing again!

I'm not sure if this is directly related, but a nice effect of this is that the [`microsite` job](https://github.com/scanamo/scanamo/blob/b2ac388cf1ffd422a6cebca64cc30d1ded5ad3b0/.travis.yml#L37-L45) for https://www.scanamo.org/ has run, and I think this might be the reason the content on the site is been updated (eg [the new Scaladex 'versions' badge](https://github.com/scanamo/scanamo/pull/1163) is showing)?

![image](https://user-images.githubusercontent.com/52038/129474968-b7baa3cc-0b17-449d-b1b8-fcf50d550dd6.png)
