### ISSUE TITLE
Table does not typecheck in presentation compiler

### ISSUE THREAD

**Issue by fommil** [scanamo/scanamo#124]
I get red squigglies with this sort of code

```
  val table = Table[MyItem]("my")
```

a workaround to get typechecking in the rest of the file is to add the type parameter

```
  val table: Table[MyItem] = Table[MyItem]("my")
```

(still a red squiggly in the RHS).

I suspect there is a bug in the macro, to add a unit test for this is quite simple, see https://github.com/ensime/pcplod I'm happy to help you get to the bottom of it.

**Comment by philwills** [comment]
Hmm, that's odd. I'm pretty sure there aren't any macros used directly anywhere in `Scanamo` at the moment, so I don't think that's the cause. 

I'll try to take a look.

**Comment by fommil** [comment]
might be the implicit resolution is too complex for the PC

**Comment by regiskuckaertz** [comment]
I cannot reproduce the problem (using ensime 🤗 ), can we close this one?

**Comment by fommil** [comment]
it's probably because your instances are trivially derived.

I think this is most likely a consequence of #135

**Comment by regiskuckaertz** [comment]
Yep, I agree. [Working on it](https://github.com/scanamo/scanamo/pull/215) 😃
