### ISSUE TITLE
disable automatic derivation

### ISSUE THREAD

**Issue by fommil** [scanamo/scanamo#135]
My team prefers semi-auto derivation as per https://github.com/fommil/stalactite

It would be great if you followed the pattern for derivation laid out in https://github.com/milessabin/export-hook to

1. avoid lots of corner cases you may not have considered
2. allow users to opt-in to full generic derivation

thanks for a great library!

**Comment by philwills** [comment]
It's something I've discussed before and it's definitely the approach I would try and take were I starting from scratch. 

I'm not planning to work on it myself imminently, but I'd be open to a PR and discussing a migration approach.

**Comment by fommil** [comment]
stalactite dramatically speeds up compiletimes, btw... we can talk about it at scala world if you're going?

**Comment by philwills** [comment]
Would love to, but I've yet again failed to organise myself to go.

**Comment by Baccata** [comment]
My team has been bitten a couple times by full-auto derivation, and we would love to see the derived formats made orphan.

**Comment by mattroberts297** [comment]
It's a shame that we cannot share some of the fun examples (and less fun work arounds) actually. Totally understand that it's not something you have time to implement at the moment though :smile:.
