### ISSUE TITLE
migrate to github action

### ISSUE THREAD

**Issue by kailuowang** [scanamo/scanamo#1356]
Looks like we ran out of luck with Travis (all credit used up and it stopped our build 20 days ago)....

**Comment by kailuowang** [comment]
For sbt ci release to continue working we need to move the secrets to github action. These are the common sonatype released credential secrets
PGP_PASSPHRASE
PGP_SECRET
SONATYPE_PASSWORD
SONATYPE_USERNAME

https://github.com/scanamo/scanamo/settings/secrets/actions

@regiskuckaertz do you happen to know who still has those secrets?

**Comment by chrislewis** [comment]
👀 🙏

**Comment by chrislewis** [comment]
Hi 👋  - sorry to nag but this will soon be a blocker for our ability to use scanamo. Any idea of timing for the next release?

**Comment by rtyley** [comment]
I've cut a release today ([`v1.0.0-M19`](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M19), [here](https://repo1.maven.org/maven2/org/scanamo/scanamo_2.13/) on Maven Central) using the old Travis CI infrastructure, so you should be able to use the benefits of #1346 now @chrislewis - but we do plan to move to GitHub Actions once we sort the new configuration out.

**Comment by chrislewis** [comment]
Thank you!

**Comment by i10416** [comment]
dup #799
