### ISSUE TITLE
Scanamo 1.0

### ISSUE THREAD

**Issue by philwills** [scanamo/scanamo#137]
Following on from #134, I'd like to get out a release based on Cats 1.0.0-MF. My plan is to use the same version for Scanamo, so it would also be `1.0.0-MF` to try and avoid confusion. Scanamo is reasonably fully featured and stable now, so whilst I'd like to move to things like #135, I'm not planning on making that kind of large change in this timeframe. 

Apart from moving to the latest versions of dependencies, the only change I'm planning is to deprecate all methods in `Scanamo` and `ScanamoAsync` apart from `exec`.  Everything they do can be achieved without much more ceremony (less if more than one operation issued) using `Table` which is more flexible, so I'd like to make it clear that that's the preferred method.

I'm very keen to hear any feedback on this approach, but want to move forward to a release quickly.

**Comment by regiskuckaertz** [comment]
That's a great move! The less there are functions with side effects, the more it encourages the programmer to push them closer to the end of the world. I like the approach of some Scala libraries to call this function `unsafeRun`; I've seen it in scalaz, cats, doobie, http4s, et al.

**Comment by fommil** [comment]
*sigh* why tie yourself to a milestone release? Binary dependency hell ensues.

The cats people were very irresponsible by trying to push a binary incompatible milestone release as some kind of final version. Even the release candidates are not realistically subject to binary compatibility until 1.0.0 is cut.

**Comment by regiskuckaertz** [comment]
@philwills I suggest we close this one now that cats 1.0 is out.
