### ISSUE TITLE
Let's release v1.0.0 and drop milestone releases!

### ISSUE THREAD

**Issue by rtyley** [scanamo/scanamo#1763]
We've been releasing milestone releases since September 2017 with [v1.0.0-M1](https://github.com/scanamo/scanamo/releases/tag/v1.0.0-M1), but I think it's time to actually stop doing this, and it wouldn't even really matter to me if the API wasn't stable or the functionality perfect, because of these two reasons:

## Milestones are considered prereleases...

So the Scaladex [lists Scanamo](https://index.scala-lang.org/scanamo/scanamo/artifacts/scanamo) as **not having pushed an artifact for the past 4 years**:

<img width="1327" alt="image" src="https://github.com/scanamo/scanamo/assets/52038/0fd68a33-6b7b-4a11-adf4-13b54ae1d89f">

## Recommended Scala SemVer Versioning Scheme

We should be using the [recommended Scala SemVer Versioning Scheme](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#recommended-versioning-scheme) - this allows users to use sbt's eviction errors much more usefully. Milestone releases mean we can't take advantage of this.

Ultimately, I would like to start using [`gha-scala-library-release-workflow`](https://github.com/guardian/gha-scala-library-release-workflow) in replacement of `sbt ci-release` - this new workflow is designed to allow us to easily perform automated syntactic compatibility checking, which automatically determines the correct version bump for the compatibility level, and has a bunch of other benefits too.

@kailuowang I'm happy to do the release - I just wanted to give you the heads up! Does this all sound ok?

**Comment by kailuowang** [comment]
Sounds good to me. Thanks for the heads-up. 
In the meantime I have to resign from the Scanamo maintainer team. I have retired and stopped coding a while ago.  Thank you again for this amazing project. Wish you all good luck!

**Comment by rtyley** [comment]
> In the meantime I have to resign from the Scanamo maintainer team. I have retired and stopped coding a while ago. Thank you again for this amazing project. Wish you all good luck!

Ah, this is sad news for us - thank you for all you excellent work as a maintainer of this library. I hope your retirement is wonderful and fun, no matter what you're doing!

**Comment by rtyley** [comment]
With [v1.0.0](https://github.com/scanamo/scanamo/releases/tag/v1.0.0) and https://github.com/scanamo/scanamo/pull/1769, this issue can be closed! ✨
