### ISSUE TITLE
Possible to stream query results, instead of loading everything into memory?

### ISSUE THREAD

**Issue by aquamatthias** [scanamo/scanamo#181]
First: Thanks for a great library!

If I read the source for `DynamoResultStream` correctly, all scan and query results are loaded completely into memory, before it can be processed. We have to deal with rather large datasets and would like to prevent OOM errors. Do you have a suggestion how it would be possible to stream the results? Ideally I would like to operate on a akka `Source[Either[DynamoReadError, T], NotUsed]`

I tried to implement a custom version of `DynamoResultStream`, but weaving this class into the existing DSL is hard / almost impossible, since all classes are private.

Any pointers would help.

**Comment by ghostdogpr** [comment]
+1 on this one, we have the exact same need

**Comment by regiskuckaertz** [comment]
Yes, it's definitely something we should address for v1. The assumption that users want _all_ the results in a single `scan` was made to avoid having to deal with DynamoDB limits, but it is problematic in too many cases. I'm thinking of adding `[scan|query]Fold`, `[scan|query]FoldM` and `[scan|query]Stream` methods.

The question is what to do with the existing `scan` and `query`? Returning a list of results without the last evaluation key feels wrong. Would you be okay with a pair `(List[A], DynamoValue)` or a custom result data type isomorphic to that pair?*

\* [`DynamoValue`](https://github.com/scanamo/scanamo/pull/400) is a pure equivalent to `AttributeValue`, it will be available in the next tag release.

**Comment by ghostdogpr** [comment]
I’d say a custom data type is best. If there was a method returning a ZIO stream, that would be awesome.

**Comment by regiskuckaertz** [comment]
I've started working on this and came up with this for the algebra:
```scala
type ScanamoOpsM[M[_], A] = FreeT[ScanamoOpsA, M, A]
trait Table[V] {
  def scanM[M[_]: Alternative](
    pageSize: Int
  ): ScanamoOpsM[M, List[Either[DynamoReadError, V]]]
}
```
Then the current `scan` can be expressed as just `scanM[List](Int.MaxInt).map(_.flatten)`.

The constraint on `M` is to allow `ScanamoOpsM[M, A] <+> ScanamoOpsM[M, A]` which, presumably for streams, would be lazy. The downside with that is if you chain other ops, they need to be lifted in `FreeT`. This can be done and the latest cats 2 release provides the handy [`toFreeT` combinator](https://typelevel.org/cats/api/cats/free/Free.html#toFreeT[G[_]](implicitevidence$1:cats.Applicative[G]):cats.free.FreeT[S,G,A]) for that.

Then in the interpreter, the user has to provide a transformation from the monad at the bottom, e.g. for ZIO:
```scala
trait ScanamoZio {
  def execM[M[_], A](hoist: FunctionK[Task, M])(op: ScanamoOpsT[A]): M[A] =
    op.foldMap(interpreter andThen hoist)
}
```

Well in fact there's not a million choices for `M` so Scanamo can provide nice defaults for `ZStream`, `Iterant`, etc.

I'm not yet 100% this is correct, but I feel positive 😄
