### ISSUE TITLE
Appending a list value does not seem to work (coerces to `List[List[...`)

### ISSUE THREAD

**Issue by prurph** [scanamo/scanamo#186]
Example:

```scala
val myList = List(1, 2, 3)
append('anExistingList -> myList)
```

This doesn't work as expected, because it casts the attribute value to a list before appending (expecting it to be a single value), so you end up trying to append `List(List(1,2,3))`. The issue seems to be here:

https://github.com/scanamo/scanamo/blob/master/scanamo/src/main/scala/com/gu/scanamo/update/UpdateExpression.scala#L145

Dynamo itself supports appending two lists (that's what Scanamo is doing here, after all), but is there a way to make this work with Scanamo? If not, any thoughts on a good way to implement it? It appears we need to know whether attribute value is a list/list-like thing or not, but I took a peek at the `DynamoFormat` and didn't immediately see a clean way to do that.

A breaking change to the `append` method, as well as adding another like `concat` or something seems yucky, but on the other hand Scanamo's current `append` signature does not match [DynamoDB's `list_append`](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.AddingListElements) which takes a list for both arguments.

**Comment by prurph** [comment]
Also I'd be delighted to work something up for this and submit a PR if you're willing and can give me an idea of what direction seems preferable (e.g. a new `concat` method vs changing the semantics of the existing `append`).

**Comment by prurph** [comment]
Messed around a bit and came up with https://github.com/scanamo/scanamo/pull/187, which adds new methods instead of changing the existing API. Let me know if these seems workable or if there's a better approach that comes to mind. Thanks!

**Comment by philwills** [comment]
Closing now #187 is merged and released.
