### ISSUE TITLE
Set up test infrastructure

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#204]
Make it possible to use things like LocalDynamoDB outside of Scanamo itself to simplify testing where you wanted to actually probe the real API.

**Comment by rtyley** [comment]
We wanted to test in Ophan that we were persisting a field correctly (DynamoDB TTL demands you store the expiration time as epoch seconds, not epoch milliseconds, d'oh!) and could really have done with some of the nice ARM methods in `com.gu.scanamo.LocalDynamoDB`.

Note also that there are two copies of this class:

* alpakka/src/test/scala/com/gu/scanamo/LocalDynamoDB.scala
* scanamo/src/test/scala/com/gu/scanamo/LocalDynamoDB.scala

cc @amyhughes
