### ISSUE TITLE
Update Expression: check if attribute exists

### ISSUE THREAD

**Issue by mirkof** [scanamo/scanamo#206]
Hi everyone,

Is it possible to check if attribute exists before setting it, to prevent overwrite? 
DynamoDB support this: [PreventingAttributeOverwrites](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.PreventingAttributeOverwrites)

Or to manually override an expression? 

Thx in advance! :)

**Comment by philwills** [comment]
@mirkof You should be able to use a condition expression, to check if an attribute already exists (see http://www.scanamo.org/conditional-operations.html)

**Comment by regiskuckaertz** [comment]
@mirkof it looks like Phil got you covered, are you happy to close this one?
