### ISSUE TITLE
Expand documentation on sealed trait families

### ISSUE THREAD

**Issue by mattroberts297** [scanamo/scanamo#210]
> Scanamo also supports automatically deriving formats for case classes and sealed trait families where all the contained types have a defined or derivable DynamoFormat.

I would like to expand on this with some examples like you have for custom formats. Assuming you agree then I will create a PR. Thanks for the library!

Specifically I was thinking:

```
import java.util.UUID

import com.gu.scanamo._
import com.gu.scanamo.syntax._

sealed trait Event
final case class Create(name: String) extends Event
final case class Delete(reason: String) extends Event

final case class DynamoRecord(id: UUID, seqNo: Int, event: Event)

val id = UUID.fromString("9e5fd6e9-65ef-472c-ad89-e5fe658f14c6")
val create = DynamoRecord(id, 0, Create("Something"))
val delete = DynamoRecord(id, 1, Delete("Oops"))

val attributeValue = DynamoFormat[DynamoRecord].write(create)

val dynamoRecord = DynamoFormat[DynamoRecord].read(attributeValue)
```

And also explaining why this on its own probably won't generate acceptable attribute values and will result in a runtime exception:

```
import java.util.UUID

import com.gu.scanamo._
import com.gu.scanamo.syntax._

sealed trait Event
final case class Create(id: UUID, seqNo: Int, name: String) extends Event
final case class Delete(id: UUID, seqNo: Int) extends Event

val id = UUID.fromString("9e5fd6e9-65ef-472c-ad89-e5fe658f14c6")
val seqNo = 0
val name = "Some Resource"
val create = Create(id, seqNo, name)
val delete = Delete(id, seqNo)

DynamoFormat[Event].write(create)
```

**Comment by philwills** [comment]
Thanks for the offer, that would be amazing. More comprehensive documentation is always very welcome. Let me know if there's anything I can clarify around how it's built.

**Comment by mattroberts297** [comment]
No worries - thanks for the awesome library.

**Comment by mattroberts297** [comment]
https://github.com/scanamo/scanamo/pull/217
