### ISSUE TITLE
Readme example doesn't work for me.

### ISSUE THREAD

**Issue by RyanSattler** [scanamo/scanamo#211]
LocalDynamoDB is not found in any of the Scanamo jars that come from importing "com.gu" %% "scanamo" % "1.0.0-M6" . Not sure if there is a dependency missing.

**Comment by mattbernst** [comment]
Code has changed and docs are outdated. See comments on this closed issue for a workaround: https://github.com/scanamo/scanamo/issues/189

**Comment by regiskuckaertz** [comment]
Hi. You can know use LocalDynamoDB in the `testkit` sub-project.
