### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mattroberts297** [scanamo/scanamo#216]
Please can you do a new release? I ask because HEAD of master uses `cats-free` [1.1.1](https://github.com/scanamo/scanamo/blob/master/build.sbt#L4) whereas 1.0.0-M6 uses `cats-free` [1.0.1](https://github.com/scanamo/scanamo/blob/a0a3e6994b19a12070ac3d5d22fbdefd511ee66d/build.sbt#L4) that in turn results in this from `sbt` (in my projects):

```
Found version conflict(s) in library dependencies; some are suspected to be binary incompatible
```

**Comment by regiskuckaertz** [comment]
M7 is now available.
