### ISSUE TITLE
Ability for clients to page through query results

### ISSUE THREAD

**Issue by shayangz** [scanamo/scanamo#223]
There are situations where results of a query can be quite large and clients would benefit from processing results in a paginated manner. dynamodb supports this type of experience by including a `LastEvaluatedKey` value in query response allowing subsequent queries to pickup where the last page ended by passing in a `ExclusiveStartKey` parameter (see [docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html)).

Exposing this information at the scanamo API level would greatly benefit clients using the library to be able to make appropriate paginated calls.

**Comment by shayangz** [comment]
@regiskuckaertz, thanks for taking this on. As part of this work, it would be fantastic to also allow the DSL to set the `ScanIndexForward` option as well. Doing so would allow clients to do pagination in either direction.

**Comment by regiskuckaertz** [comment]
Closed by #227 

(Note: `ScanIndexForward` is supported on queries: `table.query(...).descending`)
