### ISSUE TITLE
Is the `IN` operator supported in Query?

### ISSUE THREAD

**Issue by rakshith-oath** [scanamo/scanamo#224]
DynamoDb Java SDK supports `IN` comparison operator (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Comparators).

Is this operator supported in Scanamo?
If not, can we please add the support for it?

Thanks!

**Comment by regiskuckaertz** [comment]
Hello, no not yet. I've recently come across a query that would be much less expensive with `IN`, so I plan to add it.

**Comment by regiskuckaertz** [comment]
This is now supported as of M7
