### ISSUE TITLE
Scan descending

### ISSUE THREAD

**Issue by laurahk** [scanamo/scanamo#246]
Querying in descending order on the range key is implemented as follows:

`
table.query(('mode -> "Underground" and ('colour beginsWith "Bl")).descending)
`

See: https://github.com/scanamo/scanamo/commit/6a69e16b7b2ba7ed61b5af0d9c9d208a57ee9bbc

It is believed this is also implemented for scan, but I cannot find any docs/code for this. Please could someone confirm?

We are using version 0.9.1

Thanks :)

**Comment by regiskuckaertz** [comment]
Does the following compile, assuming `condition` is an expression relevant to your application:
```scala
table.scan(condition.descending)
```
?

**Comment by regiskuckaertz** [comment]
@laurahk Hello, after reviewing the documentation, DynamoDB does not support that feature on scans. It feels like an oversight on their part, but for now we can't do anything sadly.

**Comment by laurahk** [comment]
Hi @regiskuckaertz thanks for much for looking in to this and for the help previously, and sorry for not replying sooner - message got forgotten about and then left behind in my inbox.
