### ISSUE TITLE
Please publish `scanamo-cats-effect` and `scanamo-scalaz`

### ISSUE THREAD

**Issue by calvinlfer** [scanamo/scanamo#247]
Hey all, 

I noticed that these two modules weren't published (and possibly others), can you please get them published as part of the release process?

Thanks
Cal

**Comment by regiskuckaertz** [comment]
It's in the latest build already, but we haven't released yet. We probably need to automate this, at least until 1.0.

**Comment by calvinlfer** [comment]
Thanks @regiskuckaertz, you guys planning to release soon?

**Comment by regiskuckaertz** [comment]
Word on the street is cats-effect 1.0 goes out today, we could use this as an opportunity (cc @philwills)

**Comment by calvinlfer** [comment]
woop woop!

**Comment by dmitry-avershin** [comment]
@regiskuckaertz I can't find the published artifacts in maven, were they published?

**Comment by regiskuckaertz** [comment]
Yep:
https://search.maven.org/search?q=a:scanamo-cats-effect_2.12
https://search.maven.org/search?q=a:scanamo-scalaz_2.12
https://search.maven.org/search?q=a:scanamo-scalaz-zio_2.12

**Comment by dmitry-avershin** [comment]
oh, nice, I couldn't find them somehow, thx
