### ISSUE TITLE
Handle writing empty collections in DynamoFormat

### ISSUE THREAD

**Issue by Slakah** [scanamo/scanamo#253]
Follows on from https://github.com/scanamo/scanamo/pull/250 .

> An attribute value cannot be an empty String or empty Set (String Set, Number Set, or Binary Set). However, empty Lists and Maps are allowed.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes-values

**Comment by regiskuckaertz** [comment]
Closed by #250

**Comment by safwank** [comment]
Any chance this will be released in the next milestone?

**Comment by regiskuckaertz** [comment]
@safwank yes, bear with me, as I want to get [this one](https://github.com/scanamo/scanamo/pull/262) out before releasing
