### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by jcohen** [scanamo/scanamo#263]
Would it be possible to publish a new version that picks up recent changes? Specifically, I'd like to use the `queryFrom` support which was added back in July, but the last published version is from June.

Is there anything that would prevent a release being published that includes those changes?

Thanks!

**Comment by regiskuckaertz** [comment]
@jcohen yes, definitely. I want to push [this](https://github.com/scanamo/scanamo/pull/262) out and then will release.
