### ISSUE TITLE
Support `queryFrom` without an initial start key.

### ISSUE THREAD

**Issue by jcohen** [scanamo/scanamo#266]
One gap with the recent addition of `Table#queryFrom` is the ability to initiate a query that returns the next start key without specifying a start key to start with.

Ideally we'd have something like:

```scala
def queryFrom[K](query: Query[_], key: Option[UniqueKey[K]])(
    implicit K: UniqueKeyCondition[K]
  ): ScanamoOps[(List[Either[DynamoReadError, V]], Option[UniqueKey[K]])]
```

or

```
def queryFrom[K](query: Query[_]): ScanamoOps[(List[Either[DynamoReadError, V]], Option[UniqueKey[_]])]

def queryFrom[K](query: Query[_], key: UniqueKey[K])(
    implicit K: UniqueKeyCondition[K]
  ): ScanamoOps[(List[Either[DynamoReadError, V]], Option[UniqueKey[K]])]
```

Unfortunately this is not easily accomplished due to difficulties converting between the `EvaluationKey` that is returned from `QueryResultStream.stream` and a `UniqueKey` of an arbitrary type.

One option to consider is that a `Table` should inherently know its `UniqueKey`, so investigate creating the first `UniqueKey` from that information.

**Comment by regiskuckaertz** [comment]
Ok so adding the key type to the table feels like a big effort and won't solve the problem entirely. I feel like what we need to sort that out is a more powerful query:
```scala
def query0(query: Query[_]): ScanamoOps[QueryResult[A]] =
  ???
def query(query: Query[_]): ScanamoOps[List[Either[DynamoReadError, V]]] =
  query0(query).map(_.toList)
```
Then introduce `QueryResult`:
```scala
trait QueryResult[A] {
  def toList: List[Either[DynamoReadError, V]]
  def items: List[A]
  def errors: List[DynamoReadError]
  def lastEvaluatedKey[K: UniqueKeyCondition](k: K): Option[UniqueKey[K]]
}
```

**Comment by regiskuckaertz** [comment]
See #274
