### ISSUE TITLE
LocalDynamo.scala not in jar

### ISSUE THREAD

**Issue by ravi72munde** [scanamo/scanamo#277]
For some reason, I was unable to import LocalDynamo to create a client. Perhaps there was a change in API which is not documented here. I'm assuming it needs to created manually to include credentials.

**Comment by jcohen** [comment]
You need to add a dependency on [scanamo-testkit](https://search.maven.org/artifact/com.gu/scanamo-testkit_2.12/1.0.0-M8/jar) to use `LocalDynamoDb`. I agree that this is not well documented though!
