### ISSUE TITLE
AWS SDK v2  support

### ISSUE THREAD

**Issue by kaishh** [scanamo/scanamo#287]
Any plans on updating to [AWS v2 SDK](https://github.com/aws/aws-sdk-java-v2)?

**Comment by kaishh** [comment]
Well, it's [out](https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-x-released/), currently at version 2.2.0 and seems fairly complete (for dynamo)

**Comment by aesteve** [comment]
Can confirm for 2.2.0.

Careful with 2.3.x though. I've been facing date issues (with Kinesis though).

It'd be great to have "native NIO" instead of using Alpakka.

**Comment by regiskuckaertz** [comment]
Closed in favour of #395
