### ISSUE TITLE
How do I make getAll (batch) request with a partition key and a sort key?

### ISSUE THREAD

**Issue by Aqueelmiq** [scanamo/scanamo#288]
This works great, if I only need to set partition key when making a batch call
```
import com.gu.scanamo.syntax._
val getMoviesOp = movieTable.getAll('id -> ids)
```
What is the best way to create a UniqueKeys[_] from set of partition key and sort keys, if I need to set them both on my batch call? It would be nice for something like this to work.
```
import com.gu.scanamo.syntax._
val getMoviesOp = movieTable.getAll('id -> ids and 'sortkey -> sortKeys)
```

**Comment by leobenkel** [comment]
what is the solution?
