### ISSUE TITLE
Is there a way to combine a Seq of ScanamoOps into one Op programmatically?

### ISSUE THREAD

**Issue by Aqueelmiq** [scanamo/scanamo#289]
use case: combine a set of queries into one operation

**Comment by regiskuckaertz** [comment]
Hmm, do you mean to run them in parallel? if yes, that would be something the underlying monad could give you, e.g. with zio:
```scala
import scalaz.zio.IO
def parallel(ops: List[ScanamoOps[A]]): IO[DynamoReadError, List[A]] =
  IO.parTraverse(ops)(ScanamoZio.exec(client)(_))
```
otherwise you may be referring to `Table#getAll`?

**Comment by Aqueelmiq** [comment]
Yes, running in parallel would work fine for me. I will try that. Thanks!
