### ISSUE TITLE
Compilation error when too much field in case class

### ISSUE THREAD

**Issue by cbm-pvasconcelos** [scanamo/scanamo#316]
Hello, 

I use scanamo version 1.0.0M1 (I tried also on on M8 and M9...)
I've got a case class with 35 fields, when I add a field it doesn't compile anymore, i've got on error on missing implicit DynamoFormat. I get this with "sbt compile"

But when I test my Dao in one shot class in intellij, it works.

Is there a hard limit concerning the "size" of the case class ?

my case class only contains fields of Option[Double] and Option[String], no exotic objects....

thanks

Philippe

**Comment by TBonnin** [comment]
It might be related to this scala limit https://underscore.io/blog/posts/2016/10/11/twenty-two.html
@cbm-pvasconcelos Is there any code you can share for us to reproduce the issue?

**Comment by alessandrovaccaro** [comment]
I also have the same problem. I have a case class with 36 attributes. It trows the same error on the missing implicit. I have commented them all out, and reintroduced them back in one by one. It compiles fine, until I add back in the 22nd attribute.

I do use implicit DynamoFormat read/write, which have been tested and do work for my types (mostly ADTs and Value Classes).

Has anyone else here experienced an issue with large (+22 attributes) case classes?

Thank you!

**Comment by regiskuckaertz** [comment]
For this case you need to write your own `DynamoFormat`. The good news is that with the just released M10 (I promise, we will stop releasing "milestones" 😅 ) this has become easier thanks to `DynamoValue`. This is the first release and the API can definitely be improved, esp. for derivation, so please send your feedback:
```scala
implicit val caseClass36: DynamoFormat[CaseClass36] = new DynamoFormat[CaseClass36] {
  def read(v: DynamoValue): Either[DynamoReadError, CaseClass36] = for { 
    o <- v.asObject   fold(Left(MissingProperty), Right(_))
    f1 <- o("f1")     fold(Left(MissingProperty), _.as[Int])
    f2 <- o("f2")     fold(Left(MissingProperty), _.as[String])
    ...
    f36 <- o("f36")   fold(Left(MissingProperty), _.as[OtherCaseClass])
  } yield CaseClass36(f1, f2, ..., f36)

  def write(v: CaseClass36): DynamoValue = DynamoValue.fromFields(
    "f1" -> DynamoValue.fromNumber(v.f1),
    "f2" -> DynamoValue.fromString(v.f2),
    ...
    "f36" -> DynamoFormat[OtherCaseClass].write(f.36)
  )
}
```
There's definitely some work to remove boilerplate that we can do and also better error handling, but I'd appreciate if you could give it a try.

Manually writing your own typeclass instance is a must for those edge-cases: more that 22 fields, default values, internal/private/computed fields, etc.

I'll update the site asap.

**Comment by alessandrovaccaro** [comment]
Thank you, I will definitely try it! By any chance do you have any plan to add the M10 release to maven?
