### ISSUE TITLE
Use of default values for case class fields if dynamodb field is missing

### ISSUE THREAD

**Issue by tolomaus** [scanamo/scanamo#332]
Hi,

First of all many thanks for building and maintaining a library that makes my life easier :-)

I was wondering how you tackle the challenge where you need to add a new (optional) field with a default value to your case class/dynamodb table. 

if I add it as an Option to my case class:
```
case class Farmer(name: String, age: Long, isFriendly: Boolean = true) // added isFriendly
```
it's complaining about a missing when I get an already existing record from the database.

I could add the field as an explicit `Option[Boolean]` but that means that I have to write more ceremony in my code base to get at my field.

Should I create my own custom DynamoFormat and explicitly set the default value for the missing field?

**Comment by regiskuckaertz** [comment]
Hi @tolomaus 

> First of all many thanks for building and maintaining a library that makes my life easier :-)

This is so good to hear! I'm thinking, if your product is OSS or you have such license, I would really be open to promoting it on the repo/website front page!

> Should I create my own custom DynamoFormat and explicitly set the default value for the missing field?

In short, yes. Currently we are using Shapeless for automatic derivation, which (correct me if I'm wrong) doesn't have any knowledge of default values? In the future, I plan on [switching to Magnolia](https://github.com/scanamo/scanamo/pull/215) which provides more useful data.

**Comment by tolomaus** [comment]
Hi Regis,

Cool I already had a quick look at how to implement a custom DynamoFormat for my case class but the examples refer to the org.scanamo namespace which is not present in my project. Anyway if you have concrete examples of how to do this I would be happy to know about it. Otherwise I will have a closer look soon myself.

Thanks for the offer, my code base itself is not open but at least the website that's built from it is quite open (in terms of open data that is): https://openthebox.be. Just type in some Belgian politician like Guy Verhofstadt.

Many thanks for the quick response!

**Comment by regiskuckaertz** [comment]
Niiiice! I'll add that in the next update 👍 btw I'm Belgian too, how is it going on the other side of the Channel?

Heads up, the `org.scanamo` change was a longstanding one we had to do, the next official release will be under that organisation—we're just in the middle of it, sorry. Nothing else has changed though, so just replace `org.scanamo` with `com.gu.scanamo` for now and it will work.

Here's an example of a custom derivation, it's a bit involved right now but I plan to add convenience method to get rid of all the boilerplate in the future:

```scala
implicit val farmerFormat: DynamoFormat[Farmer] = new DynamoFormat[Farmer] {
  def read(av: AttributeValue): Either[DynamoReadError, Farmer] = for {
    m          <- Option(av.getM).fold(Left(NoPropertyOfType("M", av)))(m => Right(m.asScala))
    name       <- m.get("name").flatMap(_.getS).fold(Left(NoPropertyOfType("S", av)))(Right(_))
    age        <- m.get("age").flatMap(_.getN).flatMap(n => Try(n.toLong).toOption).fold(Left(NoPropertyOfType("N", av)))(Right(_))
    // ^ in the three cases above, we must have access to those fields otherwise it's a failure

    isFriendly <- m.get("isFriendly").flatMap(_.getBOOL).fold(Right(true))(Right(_))
    // ^ in this case the default value is supplied if the attribute is missing
  } yield Farmer(name, age, isFriendly)

  def write(f: Farmer): AttributeValue =
    new AttributeValue().withM(Map(
      "name" -> new AttributeValue().withS(f.name),
      "age" -> new AttributeValue().withN(f.age.toString),
      "isFriendly" -> new AttributeValue().withBOOL(f.isFriendly)
    ).asJava)
}
```

**Comment by tolomaus** [comment]
Ah nice, thanks for the example code, really appreciated!

Probably a bit calmer here - politically speaking - than at your side right night, although I don't think we're that far off ;-)

**Comment by regiskuckaertz** [comment]
Closing as M10 provides `DynamoValue` which allows easier manual derivation.
