### ISSUE TITLE
Convenience methods for manual derivation

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#336]
Peeling off the layers of an `AttributeValue` is not necessarily the best thing in life 😁 Nor is it "functional" in any way. We should aim to make writing custom `DynamoFormat` instances a breeze.

**Comment by regiskuckaertz** [comment]
Yes of course! Let's say one has a simple case class they'd like to derive:

```scala
case class A(foo: Int, bar: String)
```

I'd like to manually write a format using applicative style, something like:

```scala
val format: DynamoFormat[A] = DynamoFormat.withObject { obj =>
  obj.int("foo") <*> obj.string("bar") <@> A
} { a =>
  DynamoFormat.int(a.foo) :: DynamoFormat.string(a.bar)
}
```

It is annoying that we don't have separate `DynamoEncoder` and `DynamoDecoder` typeclasses, perhaps we should think about that.

One would have to think about all the cases: default values, derived fields, ADTs, etc. Not an easy task, but we can use this ticket to design the API. The good news is we already provide a hole of base types, all we need is expose them and add some syntactic sugar around it.

**Comment by regiskuckaertz** [comment]
This exercise is very much the same as encoding/decoding JSON, so I picked directly from the Aeson playbook. Assuming some convenience types and methods we can elaborate on later, I'm seeing something like this:

```scala
object DynamoFormat {
  def derive[A]
    ( d: Option[A],            // ^ default value
    , decode: DynamoDecoder[A] // ^ parser over AttributeValue
    , encode: A => DynamoValue // ^ value encoder
    ): DynamoFormat[A]
    = ???
}
```

### Decoding

`DynamoValue` is a pure equivalent of `AttributeValue`:

```scala
sealed abstract class DynamoValue { self =>
  def toAttributeValue: AttributeValue = ???
}

object DynamoValue {
  case object DNull extends DynamoValue
  final case class DBool(b: Boolean) extends DynamoValue
  // etc.
}
```

`DynamoDecoder[A]` is where most of the fun is, and it has to provide all the usual suspects:

```scala
class DynamoDecoder[+A] { self =>
  def map[B](f: A => B): DynamoDecoder[B]
  def flatMap[B](f: A => DynamoDecoder[B]
  def zip[B](that: DynamoDecoder[B]): DynamoDecoder[(A, B)]
  def ap[B](f: DynamoDecoder[A => B]): DynamoDecoder[B]
  // ...
}
object DynamoDecoder {
  def apply[A](value: A): DynamoDecoder[A]
  def fail(error: DynamoReadError): DynamoDecoder[Nothing]
}
```

I'm not sure yet what its concrete elaboration should be, but probably a function `DynamoValue => Either[DynamoReadError, A]` would be a good start.

In my previous comment I was using the scalaz syntax, which has been deprecated in cats. Since this package relies on the latter, its more verbose syntax should be adopted instead, i.e.:

```scala
val decoder: DynamoDecoder[A] =
  DynamoDecoder.withObject { obj =>
    ( obj.int("foo")
    , obj.string("bar")
    ).mapN(A)
  }

trait DynamoDecoder {
  def withObject(f: DynamoObject => DynamoDecoder[A]): DynamoDecoder[A]
}
```

### Encoding

This part is much easier. Most case classes will be encoded as maps, so we should have a convenience for doing so:

```scala
object DynamoFormat {
  type KeyValue = (String, DynamoValue)
  def object(p: KeyValue, ps: KeyValue*): DynamoValue = DObject(Map(p, ps))
}
```

The missing piece is a function to lift values to dynamo values:

```scala
object DynamoFormat {
  implicit def toDynamoValue[A](pair: (String, A))(implicit D: DynamoFormat[A]): (String, DynamoValue) = (pair._1, D.write(pair._2))
}
```

How does this look?

**Comment by kiranbayram** [comment]
Thanks for the explanations. I now have a better understanding what we're aiming for but I still need to look into this in more detail. I don't have much experience in this kind of FP tasks, may need some time to get comfortable with it :)

**Comment by regiskuckaertz** [comment]
I have started working on this and am close to something that works. The decoding part is ongoing. Will raise a PR soon.

**Comment by kiranbayram** [comment]
Nice, I'm looking forward to see your solution 😊
