### ISSUE TITLE
Different batchSize for dynamo batch operations

### ISSUE THREAD

**Issue by supaggregator** [scanamo/scanamo#342]
Hello, first thanks a lot for this awesome lib 👍 
When using `getWithConsistency` method, I noticed that `private val batchSize = 25`, which means `batchSize` is universal for all kinds of operations (get/write/delete).
However for "BatchGetItems", we could have a size of up to 100 items per batch. So I am wondering if we could define different `batchSize` depending operation type. Thanks for your time.

**Comment by regiskuckaertz** [comment]
Thanks a lot for your kind words 🤗 

I think that was a reasonably safe default to avoid hitting the 16MB limit. The library does not check unprocessed keys at the moment, which is necessary to avoid partial results. It is definitely something we should address 👍

**Comment by supaggregator** [comment]
Ok got it. Thanks a lot for your response! 😄
