### ISSUE TITLE
is there a way to derive DynamoDBFormat that also includes vals inside a case class?

### ISSUE THREAD

**Issue by Aqueelmiq** [scanamo/scanamo#357]
We have a trait called `DataStoreItem` that enforces our database access objects to have id and ref (pk and sk). Unfortunately, when we use `deriveDynamoFormat` to generate DynamoFormat for case classes that override these inside the case class with vals like this, it doesn't work as we would like it to.
```
case class User(
  id: String,
  name: String,
  email: String
) extends DataStoreItem {
    override val ref: String = "data"
}
```

the vals inside these case class don't get included in the serialized output that gets written into dynamoDB table. Is it possible to support something like this in an automatically/semi automatically derived fashion. We would like to use this to avoid writing custom dynamo formats for all of our classes which can quickly get error prone

**Comment by regiskuckaertz** [comment]
You will have to install `User` as a `DynamoFormat` manually or define `ref` as a `def` instead. Unfortunately, afaik Shapeless doesn't expose inner fields like that.

**Comment by Aqueelmiq** [comment]
Ok makes sense. Thanks for clarifying.

**Comment by Aqueelmiq** [comment]
I tried using defs and it still didn't get included in the serialized output.
```
case class User(
  id: String,
  name: String,
  email: String
) extends DataStoreItem {
    override def ref: String = "data"
}
```
Is there a way to include it in the automatically/semiautomatically dervied dynamo format without having to include it as one of the case class members?

**Comment by regiskuckaertz** [comment]
Not automatically no, but if we build the right DSL then it becomes trivial. Something like:
```scala
val userEncoder: DynamoEncoder[User] = DynamoEncoder { u: User =>
  Map(
    'id    -> AttributeValue.fromString(u.id),
    'name  -> AttributeValue.fromString(u.name),
    'email -> AttributeValue.fromString(u.email),
    'ref   -> AttributeValue.fromString(u.ref)
  )
}
val userDecoder: DynamoDecoder[User] = (
  DynamoFieldDecoder[String]('id),
  // ^ DynamoFieldDecoder[A] ~ Map[String, AttributeValue] => Option[A]
  DynamoFieldDecoder[String]('name),
  DynamoFieldDecoder[String]('email),
  DynamoFieldDecoder[String]('ref, "data")
  // ^ with default value
).mapN { case (id, name, email, ref) => 
  new User(id, name, email) {
    override val ref = ref
  }
}
implicit val userCodec: DynamoFormat[User] = DynamoFormat(userEncoder, userDecoder)
```

**Comment by Aqueelmiq** [comment]
thanks for the example. I think we have to go with writing the DSL manually.
