### ISSUE TITLE
One or more parameter values were invalid: An AttributeValue may not contain an empty string

### ISSUE THREAD

**Issue by Leonti** [scanamo/scanamo#366]
I'm experiencing the following error when one of my fields is an empty string:

```
One or more parameter values were invalid: An AttributeValue may not contain an empty string (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException;
```

I was very surprised to discover that DynamoDb doesn't support empty strings.
Is it supposed to work out of the box with Scanamo?
Is there a way to configure Scanamo/provide a string format to work around this issue?

**Comment by regiskuckaertz** [comment]
> I was very surprised to discover that DynamoDb doesn't support empty strings.

You have no idea 😩 We could change the string encoder to use `null` there, see if it fixes the issue.

**Comment by Leonti** [comment]
@regiskuckaertz thank you very much!
This works beautifully!
I added your string format from PR to my code and now empty strings are saved as nulls.
I hope this goes to master soon :)

**Comment by Leonti** [comment]
Now that I've tested it some more it seems like when a property is saved with `withNULL(true)` it's not creating a field, so when I'm trying to read it I'me getting:
`InvalidPropertiesError(NonEmptyList(PropertyReadError(description,MissingProperty)))`

`description` is the name of the property which contains an empty string.

**Comment by regiskuckaertz** [comment]
The last change should fix it, as the empty string is the default value for any missing field of type `String`.

**Comment by Leonti** [comment]
Can confirm that the last changes fixed the issue and I can now save and read entities with empty strings (sounds weird writing it, but I guess AWS has it's reasons for this behavior :scream: )

You are a legend, @regiskuckaertz

**Comment by regiskuckaertz** [comment]
haha 😅 thanks for bearing with us and doing all the testing! I'll merge asap and tag a new release.
