### ISSUE TITLE
jekyll installation script or documentation

### ISSUE THREAD

**Issue by kiranbayram** [scanamo/scanamo#380]
I think we should either provide a script which install jekyll or add some hints how to install it in Contributing.md

**Comment by regiskuckaertz** [comment]
That is sensible 👍 I feel like installing jekyll should just be a one-liner, so a script wouldn't be necessary and a simple mention would be enough, with a link to their site for more info. how about that?

**Comment by kiranbayram** [comment]
That should be good enough
