### ISSUE TITLE
Support CONTAINS | NOT_CONTAINS

### ISSUE THREAD

**Issue by dougdonohoe** [scanamo/scanamo#387]
I am currently evaluating Scanamo to use as our Dynamo library and am stuck at how to do a `CONTAINS` or `NOT_CONTAINS` operation.  For example, we'd like to do a filter where a Set contains or does not contain a value.

I looked at `DynamoKeyCondition` and `AttributeName` to see if I could extend Scanamo to support this myself, but it appears impossible due to the use of private and sealed classes.

Is there a way to extend Scanamo to add operators not yet supported?

Also, as a note, it would be helpful if the documentation explicitly listed and showed examples of how to do all operators.  The [query](https://www.scanamo.org/operations.html#query) section only shows `beginsWith`.

**Comment by regiskuckaertz** [comment]
Hi @dougdonohoe there is a way yes: this is an open source project, that contribution would be most welcome 🤗 

You're right with the documentation, [we'll tackle that asap](#391 ).
