### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#391]
The scanamo website is lacking in examples and does not cover the full API. Meanwhile, the scaladoc contains lots of examples which are compiled and typechecked.

I think having examples in the scaladoc does not work very well, the generated UI is ugly and hard to use. This ticket is about moving all those examples into the site itself where relevant.

I know scaladocs also contain property-based and unit tests. They should all move under the `test` folder where they belong.

**Comment by nsauro** [comment]
A lot of the links to the scaladocs are not working, either.  For example, https://www.scanamo.org/dynamo-format.html links to https://www.scanamo.org/latest/api/com/gu/scanamo/DynamoFormat$.html, which 404s.

**Comment by regiskuckaertz** [comment]
Yes, this is correct. I will fix asap, hoping to get through all those tickets during the holiday period.

**Comment by regiskuckaertz** [comment]
Tracked in #492
