### ISSUE TITLE
Support v1 and v2 of the AWS SDK

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#395]
This will require some reorganisation of the package/project structure. I propose

- `scanamo-core` is the set of types and typeclasses offered by Scanamo which does not commit to a particular SDK
- `scanamo-sdk-v1` holds interpreters and other internal structures for dealing with SDK v1
- `scanamo-sdk-v2` same for v2

While playing with the "free of free" encoding, I added a set of type to represent concrete actions:
```scala
trait ScanamoTypes {
  type ScanamoBatchGetItem[G[_]]
  type ScanamoBatchWriteItem[G[_]]
  ...
}
```
This is enough to define the class of abstract runtimes:
```scala
abstract class ScanamoRuntime[F[_]] extends ScanamoTypes {
  def batchGetItem: ScanamoBatchGetItem[F]
  def batchWriteItem: ScanamoBatchWriteItem[F]
  ...
}
```
Then for e.g. v1 we can commit to types from that sdk:
```scala
import com.amazonaws.services.dynamodbv2.model._

trait ScanamoTypesV1 extends ScanamoTypes {
  type ScanamoBatchGetItem[F[_]] = ScanamoAction[F, BatchGetItemRequest, BatchGetItemResult]
  type ScanamoBatchWriteItem[F[_]] = ScanamoAction[F, BatchWriteItemRequest, BatchWriteItemResult]
  type ScanamoCreateBackup[F[_]] = ScanamoAction[F, CreateBackupRequest, CreateBackupResult]
  ...
}
```
and define both sync and async runtimes:
```scala
import java.util.concurrent.{Future => JFuture}

abstract class ScanamoAsyncRuntime[F[_]] extends ScanamoRuntime[F] with ScanamoTypesV1 {
  def execute[Req, Res](f: Req => JFuture[Res]): ScanamoAction[F, Req, Res]

  final def batchGetItem: ScanamoBatchGetItem[F] = execute(client.batchGetItemAsync(_))
  final def batchWriteItem: ScanamoBatchWriteItem[F] = execute(client.batchWriteItemAsync(_))
  ...
}
```

Of course it won't be that easy. Right now `DynamoFormat` is tightly coupled with `AttributeValue`. However, after the [work for manual derivation](#336 ) is done, this won't be the case anymore. This ticket should probably be tackled after that.

**Comment by melgenek** [comment]
Hi @regiskuckaertz! Has there been any work done on this topic? Probably, there is a dev branch somewhere.

**Comment by regiskuckaertz** [comment]
@melgenek no, not yet, I have a draft indeed but it's going to take some time.

**Comment by lxwbr** [comment]
Is Scanamo currently supporting v2 of AWS SDK at all? If not, is there any work done in this direction?
