### ISSUE TITLE
Review project structure

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#396]
Right now we have subprojects for each interepreter: zio, alpakka, cats-effect, etc. plus a few additional ones for refined types, joda time, java time, ...

Re-structure as follows:
- `scanamo-core` is the main appeal of Scanamo: `DynamoFormat` and related, `Table`, `SecondaryIndex`, and the `DynamoValue` ADT; also generic derivation since as of Dotty it will become a first-class feature. I'd like this one to be dependency-free, or at most depend on zio-prelude. Yes, we're ditching the cats dependency and automatically make the language more powerful with less boilerplate.
- `scanamo-sync` is the synchronous interpreter
- `scanamo-future` is the Future interpreter
- `scanamo-akka-stream` is the Akka stream interpreter
- `scanamo-zio` is for the ZIO interpreter
- `scanamo-ce` is for the generic cats effect interpreter (thinking of doing `scanamo-monix` and `scanamo-fs2` directly)
- `scanamo-joda` and `scanamo-refined` remain as they are, there may be more data types that are worth considering (e.g. the spire library)

We can create a `scanamo` aggregate that brings in `core`, `sync` and `future` so that existing users can keep on using that name.

**Comment by mchv** [comment]
I think it make sense apart `-refined, -joda-time, -java-time: let's bundle that into a single scanamo-types subproject` I think ability to not depend on `joda-time` or `refined` is important to keep.

**Comment by regiskuckaertz** [comment]
Yeah that makes sense 👍
