### ISSUE TITLE
InternalServerErrorException: Internal server Error

### ISSUE THREAD

**Issue by AyushTiwary** [scanamo/scanamo#397]
I am using ScanamoAlpakka in one of my projects, and we are facing a problem i.e. any random request is failing with Internal Server Error. The occurrence of facing this exception is once or twice a month.

I am also using DynamoDB in my other projects too where we are not using Scanamo there everything works fine but this is not happening in the case of Scanamo. 

One of the example of such exception is as follow:

com.amazonaws.services.dynamodbv2.model.InternalServerErrorException: Internal server error (Service: dynamodb; Status Code: 500; Error Code: InternalServerError; Request ID: randonStringForRequestID)

**Comment by regiskuckaertz** [comment]
Hi @AyushTiwary I'm sorry to hear that, it's not good. The message isn't very helpful 🤔 Do you think you could provide an example of a query that caused the error to happen?

**Comment by AyushTiwary** [comment]
Hey @regiskuckaertz, It's not about the query. As every time it occurs randomly on any query. Even in the normal CRUD operations.
These queries even working fine in the rest of the time. Just failed with internal server error randomly on any request.

I have a few questions regarding the Scanamo implementation for DynamoDB.
Are you using one of AWS SDKs?
If Not, then Is scanamo support self retry mechanism that is by default available if we directly use the AWS SDK for DynamoDB?
As this problem is very common in case of DynamoDB. That for any millisecond, InternalServer errors are expected every once in a while, SDK clients will do automatic retries until the request goes through, to your application requests will just look successful.

**Comment by regiskuckaertz** [comment]
We are using the v1 SDK at the moment, yes. The retry mechanism is set in the client configuration, which you have to supply in order to run a scanamo op via any of the interpreters. Is it possible that the alpakka one does not give you access to it?

**Comment by AyushTiwary** [comment]
Can you please tell me how can we supply those retry configurations to the client?
As I don't find anything related to it in Scanamo documentation.
Yes, I am using ScanamoAlpakka.

I am creating the DynamaDBClient as follow:
val dynamoDBClient : DynamoClient = DynamoClient(DynamoSettings(system))
One of the sample query is as follow:
ScanamoAlpakka.exec(dynamoDBClient.m_client)(UserTable.query(PrimaryKey -> value))


Maybe this will help you to understand my issue.

**Comment by regiskuckaertz** [comment]
I'm afraid this isn't possible with that interpreter 😞 The client [is provided by the Alpakka library](https://doc.akka.io/api/alpakka/current/akka/stream/alpakka/dynamodb/DynamoClient$.html) and there is no such things as a retry policy. Do you have the opportunity to use another interpreter? If yes, then you can build an AWS client by providing a client configuration. A naive example would be:

```scala
val client = {
  val retryCondition = new PredefinedRetryPolicies.SDKDefaultRetryCondition()
  val backoffStrategy = PredefinedBackoffStrategies.EqualJitterBackoffStrategy(50, 500)
  val retryPolicy = new RetryPolicy(retryCondition, backoffStrategy, maxErrorRetry, false)
  AmazonDynamoDBAsyncClientBuilder.standard
    .withClientConfiguration(new ClientConfiguration().withRetryPolicy(retryPolicy))
    .build()
}
```

Have a look at [the docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/AmazonDynamoDBAsyncClientBuilder.html#defaultClient--) and let me know if it helps.

If switching away from Alpakka isn't an option, it means we'd have to write our own retry policy for that client, which is not on our radar right now. It's disappointing of Alplakka since they support retry for kinesis and other services.

**Comment by mavericksid** [comment]
Hi @regiskuckaertz 

I can see there's a ticket to support AWS SDK v2:
https://github.com/scanamo/scanamo/issues/395

And I can see there's already a PR for adding this compatibility:
https://github.com/scanamo/scanamo/pull/338
so it's in active development. 

Just curious, is there any ETA on AWS SDK v2 support? :)

**Comment by AyushTiwary** [comment]
Hey @regiskuckaertz 
Do you have any plans to use AWS SDK v2 as it solves all the problem? Then, I can move from Alpakka to another client.

**Comment by regiskuckaertz** [comment]
Hi both! Yes. There is work to be done for sure, but we want to support both versions for v1. I can't provide an ETA yet, sorry.

**Comment by AyushTiwary** [comment]
Thanks, @regiskuckaertz for the response. 
I am just trying to run all the test cases of Scanamo that you have using `sbt run` but facing a lot of failures.
Then I start my local DynamoDB on localhost:8042 but still not all the test cases passed.

Is there any prerequisite to successfully run the test in any machine ?

**Comment by TBonnin** [comment]
No, the only requirements is to start the local Dynamodb with the `startDynamodbLocal` sbt command.

**Comment by AyushTiwary** [comment]
We can also this now.

**Comment by AyushTiwary** [comment]
We can also close this issue now.
