### ISSUE TITLE
testkit weird org discrepancy and version

### ISSUE THREAD

**Issue by leobenkel** [scanamo/scanamo#458]
I need to import those:
```
  "org.scanamo" %% "scanamo"         % "1.0.0-M10",
  "com.gu"      %% "scanamo-testkit" % "1.0.0-M8" % Test
```

The version and the organization are not matching. 
```
  "org.scanamo" %% "scanamo-testkit"         % "1.0.0-M10",
```
does not seem to exist

**Comment by regiskuckaertz** [comment]
Hello - hmm, this is weird, the package is clearly there https://search.maven.org/artifact/org.scanamo/scanamo-testkit_2.12/1.0.0-M10/jar

**Comment by leobenkel** [comment]
What about 2.11 ?

**Comment by leobenkel** [comment]
hmm its there too https://search.maven.org/artifact/org.scanamo/scanamo-testkit_2.11/1.0.0-M10/jar
