### ISSUE TITLE
Create the table if does not exists?

### ISSUE THREAD

**Issue by leobenkel** [scanamo/scanamo#459]
How one would create the table if table does not exists ?

**Comment by regiskuckaertz** [comment]
Scanamo doesn't have that API yet, sorry.

**Comment by leobenkel** [comment]
So I should use the raw client to do that then ?

**Comment by regiskuckaertz** [comment]
Yes. I know it's ridiculous, we should add that.

**Comment by leobenkel** [comment]
haha its ok. Ill survive using some weird AWS api. Its so convoluted !

**Comment by tian000** [comment]
@regiskuckaertz are there any plans to add this?
