### ISSUE TITLE
Put succeeds but always Returns None

### ISSUE THREAD

**Issue by sfines** [scanamo/scanamo#464]
When using the latest M10 performing a basic PUT operation, it always returns None for the Option[Either[]], The expected result is a Some(Right()) since manual inspection has verified that the record is written to the LocalDynamoDB instance.

```
main: /Users/stevenfines/workspace/user-service/data/test/shared-local-instance.db
sqlite> select ObjectJSON from "test_tvp_users_api";
{"lastName":{"S":"User"},"applicationRole":{"S":"unittest"},"clientId":{"N":"1"},"createdTimestamp":{"N":"1563318931312"},"groups":{"NULL":true},"userSlug":{"S":"test_user"},"incentiveHistory":{"NULL":true},"autoApprove":{"BOOL":false},"firstName":{"S":"Test"},"permissions":{"NULL":true},"modifiedTimestamp":{"N":"1563318931312"},"id":{"N":"1"},"activeNotifications":{"NULL":true},"customAttributes":{"NULL":true}}
sqlite> 
```

Here's the code example:
```
def createUserRecord(user:User): Boolean = {
    val inserted = concurrent.Await.result(ScanamoAsync(provider.getClient).exec(table.put(user)), 5.seconds)

    if(logger.isErrorEnabled()){
     logger.error(s"Operation Result: $inserted,\nOperation Successful: ${inserted.isDefined && inserted.get.isRight}")
    }

    inserted.fold(false){
      case Left(err: DynamoReadError) => {
        logger.error(DynamoReadError.describe(err))
        false
      }
      case Right(user: User) => {
        true
      }
      case Left(x) => {
        logger.error(x.toString)
        false
      }
    }
  }
```

**Comment by TBonnin** [comment]
DynamoDB `putItem` returns the content of the old item if overwriting it. See https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html 
So if you are inserting a new item `None` is the expected result

**Comment by regiskuckaertz** [comment]
Hi @sfines - hmmm, you're right, [the operation will return the _old_ value](https://github.com/scanamo/scanamo/blob/master/scanamo/src/main/scala/org/scanamo/ops/package.scala#L96), so if there wasn't anything it will yield `None`. If we were using `ALL_NEW` instead, we could get back ... well, what you just inserted. To be frank, it always bothered me that `Put` returned anything at all. When you `INSERT` into a SQL table, all you expect is to know whether the operation succeeded or not; perhaps you might get the primary key back if auto-generated. Perhaps there should be more that one `put`:

```scala
enum Return {
  case New, Old
}

trait Table[PartitionKey, SortKey, A] {
  def put(x: A): F[Unit]
  def putAndReturn[B](x: A, ret: Return): F[A]
}
```

**Comment by sfines** [comment]
Actually, what I would prefer is that instead of returning a bare None, you returned a Some(Right(None))- this way you're keeping the semantics more or less consistent, but there is an indication that the operation was successful- as it currently stands the bare None is an ambiguous result because it _could_ be that the op succeeded but the op _could_ have failed too... I am not a fan of a Schrödinger's result.

**Comment by regiskuckaertz** [comment]
Hahaha, “Schrödinger result” I like it 😂 you’re right, this isn’t good. We’ll have a look ASAP or you’d be most welcome to submit a PR 😇

**Comment by sfines** [comment]
I'll see what I can do about getting a PR created in the near future.

**Comment by kailuowang** [comment]
I just ran into the same situation. 
The 3 obvious choices here: 
1. keep code as is, which is when there is old value return Some(Right(t)), when there is no, returns None. Add some docs to spell out the behavior. 
2, return the new value on success. The return type should be simply `T` then. 
3, make it an unit operation, the return type is simply `Unit` (failed operations result in exception as is now)

It seems to me that choice 1 provides more value than the other two, but the type signature might be misleading to users who try to understand the behavior through the type signature alone. Adding doc helps but not all users read docs for a straightforward `put`. 

So maybe another option is to provide two put methods: 

```scala
def put(t: T): ScanamoOps[Unit]

def putAndReturnOld(t: T): ScanamoOps[Option[Either[DynamoReadError, T]]]

```

**Comment by regiskuckaertz** [comment]
I prefer option 4 😅 i.e. `put` yields unit, but we provide additional facilities to return values, metrics, and/or consumed capacities.
