### ISSUE TITLE
Is there way to paginate local secondary Index

### ISSUE THREAD

**Issue by cool4lion** [scanamo/scanamo#465]
I am trying to paginate output of query on secondary Index , which operation should I use to achieve this

I tried this but getting 400 provided start Key is invalid
I look into logs 
Startkey look like below
{"arrivalTimestamp":{"N":"1563473934"},"signalId":{"S":"a7b4b7be-0663-4c5c-9dc5-6566face7bb0"},"recipientId":{"S":"abc|recipient-1"}}

val signalsList= Scanamo(client) exec(arrivalTimestampIndex.limit(20).from('recipientId -> "abc-recipient-1" and 'arrivalTimestamp -> "1563472034"  ).scan())

**Comment by regiskuckaertz** [comment]
Hi @cool4lion it looks like `arrivalTimestamp` is a number, have you tried:
```scala
val signalsList = Scanamo(client) exec {
  arrivalTimestampIndex
    .limit(20)
    .from('recipientId -> "abc-recipient-1" and 'arrivalTimestamp -> 1563472034)
    .scan()
}
```

**Comment by regiskuckaertz** [comment]
Closing but feel free to reopen if the problem persists

**Comment by eduardokhattab** [comment]
Hi @regiskuckaertz, I got stuck on that. As answered [here](https://stackoverflow.com/a/42735813/1032853), the Exclusive Start Key from an Index its composed by table keys + index keys.

I have a table whose primary key has HASH + RANGE keys. I'm also have a LSI which use another Range key.

There is a way to paginate my LSI? I cant use "_and_" twice on `from()` statement. Something like:

```scala
val signalsList = Scanamo(client) exec {
  arrivalTimestampIndex
    .limit(20)
    .from('recipientId -> "abc-recipient-1" and 'arrivalTimestamp -> 1563472034 and 'indexKey -> "foo") // doesn't compile
    .query()
}
```

**Comment by regiskuckaertz** [comment]
🤔 this is completely ridiculous and I missed that undocumented behaviour—sorry about that!

So, the best way to verify this would be to spit out the last evaluated key; imho it wouldn't make any sense if the range key for the table had to be specified in your case, since the whole point of a local secondary index is to use an alternate one.
