### ISSUE TITLE
How to execute a Put with a specific key

### ISSUE THREAD

**Issue by sfines** [scanamo/scanamo#466]
For my models, I have a compound key that I'd like to create but not concern the callers of the api - I want to do something like put('id -> generateId())(model) 

The Id's are only for generating unqiueness on persistence and have no meaning for the end users, so I don't want to include them in the model...

Is this possible?

**Comment by regiskuckaertz** [comment]
Hi Steven - hmm, that would work for insertion, but what about updates, deletes and queries? without knowing the id you're out of luck 🤔

**Comment by sfines** [comment]
I'm mostly concerned with the initial put

**Comment by regiskuckaertz** [comment]
Oh I see. My strategy in this case is usually to provide a smart constructor and hide the default one:
```scala
case class Foo private (id: String, name: String)

object Foo {
  def apply(name: String): Foo =
    Foo(generateId(), name)
}
```

**Comment by regiskuckaertz** [comment]
Closing as I think this is orthogonal to the library, feel free to reopen if you disagree.
