### ISSUE TITLE
Scanamo unable to deal with BigInteger

### ISSUE THREAD

**Issue by iyerland** [scanamo/scanamo#467]
I am trying to persist an ADT like so:
```
final case class InstalledCertDynamoItem(
  serialNumber: BigInt,
  deviceId:  UUID,
  publicKey: String,
  ts:        Long,
  ttl:       Long)
```

>  could not find implicit value for evidence parameter of type com.gu.scanamo.DynamoFormat[domain.dynamodb.InstalledCertDynamoItem]

When I remove the `serialNumber: BigInt`, it works fine! Any workaround for this?

**Comment by regiskuckaertz** [comment]
You will need to provide a `DynamoFormat` for your `BigInt`, as it is not provided by the library. You can do it like this for instance
```scala
implicit val biging: DynamoFormat[BigInt] =
  DynamoFormat.coercedXmap[BigInt, Array[Byte], NumberFormatException](BigInt(_))(_.toByteArray)
```

**Comment by iyerland** [comment]
Thanks, that worked!
