### ISSUE TITLE
Examples do not compile on 1.0.0-M10 `not found: value LocalDynamoDB`

### ISSUE THREAD

**Issue by TJC** [scanamo/scanamo#488]
The examples provided all make use of a statement like `val client = LocalDynamoDB.client()`, however the LocalDynamoDB object is not imported.

For example, see https://www.scanamo.org/, where the first example starts:
```
import org.scanamo._
import org.scanamo.syntax._
import org.scanamo.auto._
 
val client = LocalDynamoDB.client()
```

Attempting to run just that code block on Scala 2.12 with Scanamo 1.0.0-M10 will receive an error of:
```
not found: value LocalDynamoDB
```

**Comment by TJC** [comment]
Actually, I suppose I should have figured out that I needed to actually add the testkit as well...

**Comment by regiskuckaertz** [comment]
Sorry for the bad experience, the site publishing build is in bad shape at the moment while the library has evolved recently. We'll fix it asap.
