### ISSUE TITLE
Package imports names do not match between github and scanamo.org

### ISSUE THREAD

**Issue by TJC** [scanamo/scanamo#489]
There are conflicting package names given for Scanamo.

https://github.com/scanamo/scanamo/blob/master/README.md specifies:
`"org.scanamo" %% "scanamo" % "1.0.0-M10"`

However https://www.scanamo.org/ specifies:
`"com.gu" %% "scanamo" % "1.0.0-M8"`

I'm guessing that the github version is the right one to choose, but it's confusing to have both.

**Comment by TBonnin** [comment]
Good catch. PR https://github.com/scanamo/scanamo/pull/491 should fix the scanamo.org website.
