### ISSUE TITLE
Several example appear to have incorrect Scanamo `exec` syntax

### ISSUE THREAD

**Issue by TJC** [scanamo/scanamo#494]
Several examples on the Scanamo site use the following syntax, but it doesn't compile.

```
Scanamo.exec(client)(operations)
```

On version `1.0.0-M10` of Scanamo, it appears that the correct syntax is:
```
Scanamo(client).exec(operations)
```

**Comment by regiskuckaertz** [comment]
Thanks for this! Closing in favour of #492 , please feel free to add items if you find anything.
