### ISSUE TITLE
Release plans for 1.0.0

### ISSUE THREAD

**Issue by markus1189** [scanamo/scanamo#574]
Hey :wave:,

are there specific plans/roadmap when the `1.0.0` version will be released?  
Or the next milestone?  The last one (M11?) is already quite old and is missing e.g. the new magnolia derivation.

**Comment by regiskuckaertz** [comment]
Hello @markus1189 🤗 

I'll release another milestone, [this](https://github.com/scanamo/scanamo/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0) is the plan for 1.0. I've been busy at work but I'll have more time to focus on Scanamo at the beginning of February, so I can go through these.

**Comment by markus1189** [comment]
Having another milestone would be good :hugs:  Because without working derivation of `DynamoFormat` we don't want to use e.g. `M11` :cry:

**Comment by markus1189** [comment]
Thanks, with `M12` we are unblocked, closing this!
