### ISSUE TITLE
Proposal: Split DynamoFormat into separate scanamo library

### ISSUE THREAD

**Issue by markus1189** [scanamo/scanamo#575]
In some of our projects, we don't want to use the whole functionality of `Scanamo`.  We only need the mapping from case classes (and other types) to Dynamo, i.e., exactly what `DynamoFormat` does.

Would you be open to the proposal to split the whole `DynamoFormat` functionality into a separate library (like `scanamo-format` or sth like that)? Or are there any concerns about the separation? Any other notes if somebody wants to try it?

**Comment by regiskuckaertz** [comment]
Hmm, that is interesting. My plan was to have a `scanamo-core` which defines the data types and algebras, but no single runtime. That would include `DynamoFormat`, `DynamoValue`, `Table` and the free stuff.

Is it that the `Table` DSL is unappealing to you? It would be very useful for me to know if there is something in the library that is not intuitive as I start planning 2.0.

**Comment by markus1189** [comment]
In some smaller services we don't have fancy requirements for e.g. the dynamo access, so we just use the AsyncDynamodbClient from the aws sdk v2.  It's nice because we can dramatically reduce the footprint of transitive dependencies (avoid dependency hell with e.g. conflicting akka versions :roll_eyes: ).

**Comment by regiskuckaertz** [comment]
Yes 😞 I think moving to v2 of the SDK will have to wait until 1.0 is out.

**Comment by regiskuckaertz** [comment]
@markus1189 hi mate - long time no see. So here are my thoughts around this. I think the appeal of scanamo is the table/index DSL, the wrapper around the AWS client can be abstracted so people could plug their own (I'm really thinking about writing a client that has zero dependency on AWS). I suggest we close this ticket in favour of #396 , where I will be collating all the latest around this.

**Comment by regiskuckaertz** [comment]
Feel free to reopen if you disagree.

**Comment by markus1189** [comment]
Hey @regiskuckaertz I'm fine with closing this!

Thanks for the comment :)
