### ISSUE TITLE
Throttling: "Throughput exceeds the current capacity of your table or index" with async client and On-Demand mode

### ISSUE THREAD

**Issue by pederpansen** [scanamo/scanamo#589]
Hi. First of all thanks for providing this great library with a very clean and easy-to-use API.

I just started using DynamoDB for some batch insert workload. Since I don't know my capacity requirements yet, I chose the On-Demand mode. However, I can't seem to prevent write loss.

I'm using the async version of the API in conjunction with Alpakka DynamoDB `1.1.2`:

```
val asyncDynamoDbClient = DynamoClient(DynamoSettings(actorSystem))
```
1) when using the latest release `1.0.0-M12-1`:

```
val sc = ScanamoAlpakka(asyncDynamoDbClient, RetryPolicy.exponential(500.milliseconds, 2.0))
val result: Future[Unit] = sc.exec(rawSkuTable.putAll(skus)) }.runWith(Sink.last)
```
If I call this code in a loop with batches of a few hundreds of items, I am getting instances of `AmazonDynamoDBException`:

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html (Service: dynamodb; Status Code: 400; Error Code: ThrottlingException;
...
```

I would expect the exponential retry policy to take care of retrying and eventually succeeding, what am I doing wrong here?

2) when using the release `1.0.0-M10`:

```
val sc = ScanamoAlpakka(asyncDynamoDbClient, RetryPolicy.Exponential(500.milliseconds, 2.0))
val result: Future[Unit] = sc.exec(rawSkuTable.putAll(skus)) }.runWith(Sink.last).map{ result =>
      val numUnprocessed = result.map(_.getUnprocessedItems.size).sum
      if(numUnprocessed > 0) {
        throw new MyException(s"Could not write ${numUnprocessed} of ${skus.size} raw skus to DynamoDB")
      } else
        logger.info(s"Successfully wrote ${skus.size} raw skus to DynamoDB")
        Unit
}
```

In this version, at least the unprocessed items are returned, so that I can throw a custom exception (and possible retry unprocessed items only). However, sometimes my custom exception is not called and the above `AmazonDynamoDBException` is thrown instead.

I am having a hard time figuring out how to avoid write loss. Do I need to wrap my code into a custom retry-loop? If yes, what would that look like? What can I expect from the retry policies? Would the sync client API work better for such a case? The docs seem to be outdated for the versions I tried, so I'm not sure if I'm using it as intended. 

And finally, would a version of this library based on the v2 version of the AWS Java SDK make using custom retru policies obsolete, as retrying and throttling is taken care of by the AWS library iteself?

If I ditch the On-Demand mode and switch to Provided Mode, that might help, but sooner or later, with increased workload, I might find myself at the same point of getting throttled.

Sorry for asking lots of questions!

**Comment by regiskuckaertz** [comment]
Hi @pederpansen 

Not at all! It's great to have feedback and thank you so much for providing very detail analysis of your use case.

1. that exception should definitely get picked up. I will play around with your code to see where the library breaks it promises.

2. it looks like a bug, if this behaviour is not consistent we may have missed a test case to capture it. Sorry about that, you shouldn't have to write your own retry logic.

I'll have a look at this during the weekend and keep you updated.

**Comment by pederpansen** [comment]
Thank you @regiskuckaertz, your help is much appreciated. 

I just switched my table to Provisioned Mode and my batch import got through, so maybe there is something different regarding the retry mechanism when using On-Demand Mode.

**Comment by pederpansen** [comment]
Oh, and if I might add to my list of questions: Is there any reason for return `Unit` when using the `deleteAll` / `putAll` methods? In a previous version, there would have been a return value containing some info about the number of _actually_ processed items, which I find helpful for logging/monitoring purposes.

**Comment by regiskuckaertz** [comment]
I find troubling that a purely functional library exposes mutable types, which is why I switched to `Unit`, though I admit this is going too far in the opposite direction 😅 I fell short of recreating case classes for all dynamo data types, which is probably what i should have done, in the same fashion as elastic4s for instance.

Until now I've been quite liberal in my changes because it's still not officially 1.0 and thus I can break contracts. But now is time to fix these things once and for all, or at least until 2.0.
