### ISSUE TITLE
Please add query with params to ScanamoFree

### ISSUE THREAD

**Issue by Ravenow** [scanamo/scanamo#595]
Guys, could you add to ScanamoFree method with access to  all query options, something like this
```scala
object ScanamoFree {

  type QueryResult[K, V] = (List[Either[DynamoReadError, V]], Option[Either[DynamoReadError, K]])
 
  //...

  def queryWithParams[K, T](t: Table[T])(
      index: Option[String],
      query: Query[_],
      options: ScanamoQueryOptions
  )(implicit kf: DynamoFormat[K], tf: DynamoFormat[T]): ScanamoOps[QueryResult[K, T]] =
    QueryResultStream
      .stream[T](ScanamoQueryRequest(t.name, index, query, options))
      .map({
        case (v, ko) => (v, ko.map(k => kf.read(k.toDynamoValue)))
      })
 //...
}
```

**Comment by regiskuckaertz** [comment]
hi @Ravenow 

Would you be kind enough to let me know what use case the `Table` query DSL does not solve that you need access to the underlying data types?

That would be super useful 🙏 There are a few things that bother me with the current API, mostly that there is not typing for keys and no proof one can extract a key from a record (which is why you have to universally quantify on `K` 😞 ).

Also: are you directly using `ScanamoFree` methods?

**Comment by Ravenow** [comment]
I just wanna query secondary index with filter condition and some sort of "pagination"

```scala
val scanamo: ScanamoCats[F] = ???
val devices: Table[Value] = ???

  def indexQuery(
      query: Query[_],
      filter: Option[Condition[_]],
      limit: Int,
      startKey: Option[StartKeyValue]): F[QueryResult[StartKeyValue, Value]] = {
    val startKeyObj = startKey.map(DynamoFormat[StartKeyValue].write).flatMap(_.asObject)
    val queryOptions = ScanamoQueryOptions.default.copy(
      limit = limit.some,
      filter = filter,
      exclusiveStartKey = startKeyObj
    )
    scanamo.exec(queryWithParams(table)(index.some, query, queryOptions))
  }

```

**Comment by regiskuckaertz** [comment]
Ha, pagination is back! Excellent topic, as recently I introduced `scanPaginatedM` and `queryPaginatedM` and was wondering if there were existing users out there. Have you seen and/or tried them out already?

**Comment by Ravenow** [comment]
Yeah, i seen them, but from my point of view there is no way to specify filter and startKey. Also for me its not clear how to extract key from response in methods you mentioned :)

**Comment by regiskuckaertz** [comment]
Yes, fair enough. I think we just need to add a more generalised version of those APIs that allows you to stop in the middle. Adding a callback that receives the start key should be enough. As for the filter, indeed this is more complex 🤔 Let me think about it.

**Comment by Ravenow** [comment]
I think it will be a good tradeof if there would be fancy dsl for common things, but when there is need to dive deeper u could use some advanced api with all features available. 

PS: Wanna mention that i wouldnt post any issues here if scanamo internals not private :)) Because for now there is no way to add extension methods(via implict classes) or change behaviour without copy&paste some part of scanamo internals into the project.

**Comment by regiskuckaertz** [comment]
@Ravenow hi, sorry for the delay. You can use `table.from(key).scan0` for example. `scan0`/`query0` produce the raw result, while `from` allow you to set a starting key.
