### ISSUE TITLE
ConditionExpression.prefixKeysIn doesnt work properly if there are more then 10 params

### ISSUE THREAD

**Issue by Ravenow** [scanamo/scanamo#597]
Im using filter for query index with AND condition, one of them eq condition, other in condtion. When you pass to "in query" more then 10 params for example, subj method doesn`t work well, looks like result.replaceAllLiterally actually replace twice for params with idx > 10

Im using scanamo-1.0.0-M12-1

Thanks

**Comment by regiskuckaertz** [comment]
Good catch! I will publish a fix asap, thanks a lot for reporting the issue.

**Comment by Ravenow** [comment]
i would really appreciate you if you`ll publish fix version to maven repos for it :) ofcause in case of real bug here.
