### ISSUE TITLE
release for scala 2.13

### ISSUE THREAD

**Issue by Marcus-Rosti** [scanamo/scanamo#647]
Nexus central doesn't have scanamo for 2.13
https://mvnrepository.com/artifact/com.gu/scanamo

**Comment by Marcus-Rosti** [comment]
found it:
https://search.maven.org/artifact/org.scanamo/scanamo_2.13/1.0.0-M12-1/jar

**Comment by Marcus-Rosti** [comment]
sorry!

**Comment by regiskuckaertz** [comment]
no worries 🤗
