### ISSUE TITLE
cannot disable auto-derivation of formats

### ISSUE THREAD

**Issue by dwunsch** [scanamo/scanamo#673]
to avoid surprises, i prefer semiautomatic derivation over the automatic one.

therefore, i'd expect code like this failing to compile: 
```
sealed trait A; case object A1 extends A; case object A2 extends A
final case class B(a:A)

import org.scanamo.generic.semiauto._
// this should not work, because i forgot to declare a DynamoFormat for A anywhere
implicit val B_Format:DynamoFormat[B] = deriveDynamoFormat
```

for some reason, this is not the case:
somehow a codec for A ist still autoderived so when i write a B into my table, scanamo happily encodes this into something like `a:{A1:"A1"}` into my table - which is not what i wanted.

can and should this be changed? in e.g. circe, this _would_ have failed at compile time.

**Comment by regiskuckaertz** [comment]
Hmm, yeah that sucks. I looked into the magnolia derivation and I see why this is happening. Oh boy, that's going to be a fun ride 😓
