### ISSUE TITLE
New official release

### ISSUE THREAD

**Issue by yaelm-carbyne** [scanamo/scanamo#732]
Hi,

When there will be a new official release?

Thanks,
Yael

**Comment by semenodm** [comment]
also is there nightly builds? I have one library with critical update related to the DynamoDB SDK v2  migration

**Comment by regiskuckaertz** [comment]
Keen to release, I just need to find the time and get sth weird with Travis sorted.

**Comment by lxwbr** [comment]
Also very looking forward to this for the SDK v2 part
