### ISSUE TITLE
Can't Get Items

### ISSUE THREAD

**Issue by rubenssoto** [scanamo/scanamo#885]
Hello Guys,

probably I'm doing something wrong
On this part
val files = Table[file]("table_name")

I got error: could not find implicit value for evidence parameter of type org.scanamo.DynamoFormat[scanamo.file]

and on this 

  Scanamo.exec(client)(operations)

I got this error: 

value exec is not a member of object org.scanamo.Scanamo

Could you help me?

Thank you

**Comment by regiskuckaertz** [comment]
Try `Scanamo(client).exec(operations)` (yes, sadly the documentation is outdated)
