### ISSUE TITLE
Inconsistent website documentation

### ISSUE THREAD

**Issue by LukeDeighton** [scanamo/scanamo#886]
I tried upgrading Scanamo but noticed quite a few changes in the API that are not reflected in the documentation on the website.

Firstly the github readme recommends going to:
`libraryDependencies += "org.scanamo" %% "scanamo" % "1.0.0-M10"`

but the website still says this, with the old package space
`libraryDependencies += "com.gu" %% "scanamo" % "1.0.0-M8"`

I tried upgrading to 1.0.0-M10 but the documentation is incorrect.
The website suggests:
`Scanamo.exec(client)(operations)`

but it appears the new approach is:
`Scanamo(client).exec(operations)`

Think it would be worth going through the documentation and tidying it up or correcting it as I guess there's quite a few tiny differences with the evolving API

**Comment by regiskuckaertz** [comment]
Hi @LukeDeighton I couldn't agree more, it's something I've been terrible at, apologies for that. I will close this ticket as this is tracked in #492 , hoping someone will pick it up soon!
