### ISSUE TITLE
Cut new release to fix High severity vulnerability

### ISSUE THREAD

**Issue by kittsville** [scanamo/scanamo#947]
Could you release a new version of Scanmo? This would fix the high severity vulnerability in `1.0-M13`, introduced by  `org.apache.httpcomponents:httpclient@4.5.12` via DynamoDB?

You're using the latest DynamoDB so the fix is already in master.

[Vulnerability summary](https://snyk.io/vuln/SNYK-JAVA-ORGAPACHEHTTPCOMPONENTS-1048058)

**Comment by davidfurey** [comment]
Thanks for pointing out this security vulnerability.  I've released v1.0-M14
