### ISSUE TITLE
Support empty string attributes

### ISSUE THREAD

**Issue by danielchen2** [scanamo/scanamo#968]
As per https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/

Empty string attributes have been supported since May 18 2020. Right now they are serialised to NULL as per https://github.com/scanamo/scanamo/pull/367.

This should be a pretty easy fix, happy to open a PR to help.

**Comment by davidfurey** [comment]
Hi @danielchen2 

Thanks for opening this issue. A PR would be really appreciated.

**Comment by davidfurey** [comment]
Thanks @danielchen2
